import type { Metadata } from "next";
import { Geist as GeistFont, Geist_Mono as GeistMonoFont } from "next/font/google";
import "./globals.css";

const geistSans = GeistFont({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = GeistMonoFont({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Analytics } from "@vercel/analytics/next";

import { ThemeProvider } from "@/components/theme-provider";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {children}
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
